# Generated by Django 4.2.6 on 2023-10-23 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 23, 13, 17, 9, 582407, tzinfo=datetime.timezone.utc)),
        ),
    ]
